#include "stdafx.h"
#include "Word_Frequency.h"

// Read all word into a map in the form: (Word, Number of Appearence)
void CountWordFrequencyFromFile(const char *Path, map<string, size_t> & word_count)
{
	ifstream fin(Path);
	string word;
	while (fin >> word)
		++word_count[word];
	fin.close();
}

// Sort the word frequency generated by function CountWordFrequencyFromFile()
set<pair<string, size_t>, function<bool(pair<string, size_t>, pair<string, size_t>)>>
SortWordFrequency(const map<string, size_t> & word_count)
{
	typedef function<bool(pair<string, size_t>, pair<string, size_t>)> CmpType;
	CmpType Cmp = [](pair<string, size_t> a, pair<string, size_t> b) {
		return a.second > b.second;
	};

	set<pair<string, size_t>, CmpType> word_freq(word_count.begin(), word_count.end(), Cmp);

	return word_freq;
}